ktor:
  application:
    modules:
      - it.marcointroini.ApplicationKt.module
  deployment:
    host: "$HOST:0.0.0.0"
    port: "$PORT:8080"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
