ktor:
  application:
    modules:
      - it.marcointroini.ApplicationKt.module
  deployment:
    host: "$HOST:0.0.0.0"
    port: "$PORT:8080"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
database:
  url: "$DB_URL:jdbc:postgresql://localhost:5432/codersee_users"
  user: "$DB_USER:root"
  password: "$DB_PASSWORD:"
